### PR TITLE
Document tmap, remove Manifest.toml, remove Julia 0.6 support

### PR DESCRIPTION
**Pull request by jw3126**
Properly removing 0.6 support, which does not pass all tests anyway. Some other minor improvements.

### CODE REVIEW

**Comment by mohamed82008** [comment]
Looks good to me, but I think the Manifest file is important since it is used in Travis tests. If a test fails on Travis, you are more likely to reproduce it locally when using the same Manifest.

**Comment by jw3126** [comment]
I think its almost always bad practice to commit the `Manifest.toml`. It pollutes the git diffs and makes installing multiple packages in a single environment hard.

**Comment by mohamed82008** [comment]
> and makes installing multiple packages in a single environment hard.

How is that?

**Comment by jw3126** [comment]
I am not completly sure, but I think if you install a package that ships with a Manifest file then versions of its dependencies in the environment are constrained by the Manifest file?

**Comment by jw3126** [comment]
Okay, I think that was superstition on my part, see also [here](https://discourse.julialang.org/t/does-manifest-toml-belong-in-the-repository/12029) for a list of pros and cons. So I can add the Manifest again.

**Comment by mohamed82008** [comment]
> then versions of its dependencies in the environment are constrained by the Manifest file?

No this is not the case.

Thanks for your understanding :)

**Pull request merged**
